#! /bin/bash

source common-setup

echo "##### Using `python3 --version`"

echo "##### Installing virtualenv"

if ! python3 -c "import subprocess, sys; subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'virtualenv'])" > /dev/null 2>&1 ; then
  echo "##### Failed to install virtualenv"
  exit 1
fi

echo "##### Creating a virtual environment"

python3 -m venv "$FORENSICS_DIR/compilers/venv"

echo "##### Installing forensics.collector"

$FORENSICS_DIR/compilers/venv/bin/pip install -e $FORENSICS_DIR/../py-forensics
