#! /bin/bash

. server-common

echo "Creating virtualenv..."
python3 -m venv "${PWD}/../venv"

echo "Installing py-forensics python package..."
$PIP install -e "${PWD}/../py-forensics/"

cp "${PWD}/../py-forensics/forensics/templates/example.conf" "${PWD}/../forensics.conf"
echo "Done. Please edit ${PWD}/../forensics.conf"
